### ISSUE TITLE
JavaScript insded book breaks the sidebar links

### ISSUE THREAD

**Issue by hansgru** [xgrommx/rx-book#8]
There seems to be some sort of JS in the "book content" that breaks the entire book sidebar navigation after a while (under Firefox at least).

Initially when the book is loaded, the links in the sidebar are correct. After clicking a few of them however, some of them change, having 
```
http://xgrommx.github.io/rx-book/content/how_do_it/..%5C../content/how_do_it/jquery_with_rxjs.html
```
that stuff in the middle, thus rendering the book practically useless.

**Comment by mlangc** [comment]
The links are still broken in Firefox (36.0.4 on Mac). Clicking on "RxJS Design Guidelines" for instance leads to http://xgrommx.github.io/rx-book/content%5Cguidelines%5Cindex.html (with '\' instead of '/') instead of the correct URL wich is http://xgrommx.github.io/rx-book/content/guidelines/index.html.
